
all:
	rm -f scene.lua
	rm -f scene2.lua
	rm -f scenemanager.lua
	
	fennel --compile scene.fnl > scene.lua
	fennel --compile scene2.fnl > scene2.lua
	fennel --compile scenemanager.fnl > scenemanager.lua